//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectReq
    {
        public int Id { get; set; }
        public string FoodName { get; set; }
        public int RId { get; set; }
        public System.TimeSpan MaxPresTime { get; set; }
        public int StatusId { get; set; }
        public int EmpId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurent Restaurent { get; set; }
        public virtual Status Status { get; set; }
    }
}
